### ISSUE TITLE
这个模块刷入后会备份原来的字体吗？

### ISSUE THREAD

**Issue by goodnull** [varieget/SFFonts#1]
这个模块刷入后会备份原来的字体吗？
或者可以恢复之前系统默认的字体吗？

**Comment by varieget** [comment]
大部分 magisk 模块，在移除后并重启手机，就会恢复到没安装那个模块前的样子的。
如果要恢复之前系统默认的字体，移除该模块并重启即可。

部分系统，例如 MIUI 要使用 magisk 字体模块，需要刷入空字体模块（在酷安上有）及其主题，并在字体设置选中空字体，才会生效。

**Comment by goodnull** [comment]
> 大部分 magisk 模块，在移除后并重启手机，就会恢复到没安装那个模块前的样子的。 如果要恢复之前系统默认的字体，移除该模块并重启即可。
> 
> 部分系统，例如 MIUI 要使用 magisk 字体模块，需要刷入空字体模块（在酷安上有）及其主题，并在字体设置选中空字体，才会生效。

感谢，我刷入后重启字体就生效了，没有刷空字体模块
