### ISSUE TITLE
请问这个字体能更新吗？

### ISSUE THREAD

**Issue by syx-413** [varieget/SFFonts#2]
https://github.com/ACT-02/PingFang-for-Windows

**Comment by varieget** [comment]
他那个是 macOS 15 Sequoia beta 1 提取的 20.0d3e1 如果不急着用的话，可以等秋季 macOS 15 正式版出了在说

没记错的话，macOS 14 Sonoma 的 PingFang.ttc 不用做额外的操作，就可以直接被 Windows 导入，这个仓库 `system/fonts/PingFang.ttc` 下的 PingFang.ttc 就是 macOS 14 的
